name: magic_8_ball
description: A fun, mini decision making app


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: lib/fonts/RobotoMono-Regular.ttf
    - family: RobotoMono
      fonts:
        - asset: lib/fonts/RobotoMono-Italic.ttf


  uses-material-design: true

  assets:
    - lib/images/


